# Generated by Django 4.2.3 on 2023-07-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('CORPORATE EADOFFICE', 'CORPORATE EADOFFICE'), ('OPERATION DEPARTMENT', 'OPERATION DEPARTMENT'), ('MARKETING DIVION', 'MARKETING DIVION')], max_length=50)),
                ('incident_description', models.CharField(max_length=300)),
                ('made_on', models.DateField()),
                ('incident_location', models.CharField(max_length=300)),
                ('initial_severity', models.CharField(choices=[('MILD', 'MILD'), ('MODARATE', 'MODARATE'), ('SERVER', 'SERVER'), ('FATAL', 'FATAL')], max_length=50)),
                ('suspected_cause', models.CharField(max_length=300)),
                ('immediate_actin_taken', models.CharField(max_length=300)),
                ('sub_incident_type', models.CharField(max_length=300)),
                ('reported_by', models.CharField(max_length=100)),
            ],
        ),
    ]
